dist: jammy
language: cpp
compiler:
  - clang
addons:
  apt:
    packages:
      - libboost-test-dev
      - libspdlog-dev
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: releases
  api_key: $GITHUB_AUTH_KEY
  file: cmake_travis-0.0.9$TRAVIS_BUILD_NUMBER-Linux.deb
  skip_cleanup: true
  on:
    master: true