dist: xenial
language: cpp
compiler:
  - clang
addons:
  apt:
    packages:
      - libboost-test-dev
      - libspdlog-dev
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -f -T cmake_travis-0.0.9$TRAVIS_BUILD_NUMBER-Linux.deb -uaminjonshermatov:$BINTRAY_API_KEY "https://api.bintray.com/content/aminjonshermatov/cpp_travis/$TRAVIS_BUILD_NUMBER/cmake-0.0.9$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"